/**
 * Emits packages/sim/src/trig.table.ts.
 *
 * The table cannot be built at load time: packages/sim is forbidden from
 * calling Math.sin, and even if it were allowed, Math.sin is not specified to
 * bit-identical precision across JS engines. Baking the samples into a
 * checked-in literal makes the table identical on every platform by
 * construction, and makes any change to it show up in a diff.
 *
 * Number#toString already produces the shortest string that round-trips to the
 * same double, and ECMAScript specifies string-to-double as correctly rounded,
 * so these literals reload bit-exact in every engine.
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const SIZE = 4096;

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../../../packages/sim/src/trig.table.ts');

const samples: string[] = [];
for (let i = 0; i < SIZE; i++) {
  samples.push(String(Math.sin((2 * Math.PI * i) / SIZE)));
}

// 12 per line keeps the file readable in a diff without exploding line count.
const lines: string[] = [];
for (let i = 0; i < SIZE; i += 12) {
  lines.push('  ' + samples.slice(i, i + 12).join(', ') + ',');
}

const body = `// GENERATED by tools/codegen/src/trig.ts. Do not edit by hand.
// ${SIZE} samples of sin over [0, 2pi). See trig.ts for why this is baked.

export const TRIG_TABLE_SIZE = ${SIZE};

export const SIN_TABLE: readonly number[] = [
${lines.join('\n')}
];
`;

writeFileSync(out, body, 'utf8');
process.stdout.write(`wrote ${out} (${SIZE} samples)\n`);
